name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make
          sudo apt-get install -y \
            libfreetype6-dev \
            libx11-dev \
            libxrandr-dev \
            libgl1-mesa-dev \
            libudev-dev \
            libopenal-dev \
            libflac-dev \
            libogg-dev \
            libvorbis-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release
